# Generated by Django 4.2.7 on 2023-12-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('userid', models.CharField(max_length=25, unique=True, verbose_name='아이디')),
                ('name', models.CharField(max_length=30, verbose_name='회사 이름 혹은 이름')),
                ('email', models.EmailField(max_length=50, verbose_name='회사 이메일 혹은 이메일')),
                ('phone', models.CharField(max_length=13, unique=True, verbose_name='회사 번호 혹은 번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='로그인 가능')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='최고관리자')),
                ('is_staff', models.BooleanField(default=False, verbose_name='관리자페이지 접근')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='로그인 일시')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록 일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name_plural': '사용자',
                'db_table': 'myuser',
            },
        ),
    ]
